### ISSUE TITLE
Describe how to configure the MQTT broker url for dockerized module

### ISSUE THREAD

**Issue by JuergenKosel** [edgexfoundry/device-mqtt#18]
Hello,

could you please describe how to configure the URL of the broker etc. if the device-mqtt module runs in a docker container.

I _guess_ it results into something like
`docker run -v=application.properties:/edgex/edgex-device-mqtt/application.properties edgexfoundry/docker-device-mqtt`

Greetings
  Juergen

**Comment by jpwhitemn** [comment]
@JuergenKosel  - there isn't anything that allows for supplying custom application properties at this time.  You could build your own per https://wiki.edgexfoundry.org/display/FA/MQTT+Device+Service+-+How+to+use%2C+configure%2C+and+where+to+customize and then repackage the docker container.  You could also seed consul with changed properties and allow the service to pick them up from Consul on startup (overriding the existing properties).  More work will be completed on new SDKs (in Go and C) this summer.

**Comment by JuergenKosel** [comment]
Hello,

I have already customized the device-mqtt container with the attached docker-compose file.
[docker-compose.txt](https://github.com/edgexfoundry/device-mqtt/files/2088849/docker-compose.txt)
This way I have successfully replaced the application.properties file in the container. So that the device-mqtt connects to my local broker.

**Comment by jpwhitemn** [comment]
@JuergenKosel - I suggest you submit a PR and contribute the proposed docker-compose file to the device-mqtt repo (putting it the docker-files folder and add just a bit of documentation to the top of the file to suggest how/why use it).  With the PR, we can close out this issue.  Sound acceptable?
