### ISSUE TITLE
'randnum' core command does not work

### ISSUE THREAD

**Issue by giovannipersia** [edgexfoundry/device-mqtt#24]
Hi All,

i followed the Get EdgeX Foundry – Users guide to install and configure the minimal EdgeX on an Ubuntu machine using docker tool.

Below the microservice list that i used:

•	edgexfoundry/docker-core-metadata-go:0.6.0
•	edgexfoundry/docker-core-data-go:0.6.0 
•	edgexfoundry/docker-core-command-go:0.6.0
•	edgexfoundry/docker-edgex-mongo:0.6.0
•	device-mqtt (Java version 0.5.0, branch master)

Afterwards i followed the MQTT Device Service example guide (link: https://github.com/edgexfoundry/edgex-go/blob/master/docs/examples/Ch-ExamplesMQTTDeviceService.rst) to understand how this framework works.

I managed to receive data on device-mqtt microservice using the TestMqttDeviceSendor.java class but I cannot to receive any command from EdgeX using TestMqttDeviceSendor.java class.

Below the output of http://localhost:48082/api/v1/device/name/TestMQTTDevice API to get all the commands for the device:

ubuntu@ip-10-0-2-201:~$ curl -v -o - http://localhost:48082/api/v1/device/name/TestMQTTDevice
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 48082 (#0)
> GET /api/v1/device/name/TestMQTTDevice HTTP/1.1
> Host: localhost:48082
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 17 Sep 2018 15:33:36 GMT
< Transfer-Encoding: chunked
<
{
                    "id": "5b9f71e09f8fc200016aa37b",
                    "name": "TestMQTTDevice",
                    "adminState": "UNLOCKED",
                    "operatingState": "ENABLED",
                    "lastConnected": 1537188293742,
                    "lastReported": 0,
                    "labels": ["thermostat", "industrial"],
                    "location": "{lat:45.45,long:47.80}",
                    "commands": [{
                                       "created": 1535722249629,
                                       "modified": 0,
                                       "origin": 0,
                                       "id": "5b8943099f8fc200016aa372",
                                       "name": "testrandnum",
                                       "get": {
                                                           "path": "/api/v1/devices/{deviceId}/randnum",
                                                           "responses": [{
                                                                               "code": "200",
                                                                               "description": null,
                                                                               "expectedValues": ["randnum"]
                                                           }, {
                                                                               "code": "503",
                                                                               "description": "service unavailable",
                                                                               "expectedValues": []
                                                           }],
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa372"
                                       },
                                       "put": {
                                                           "path": null,
                                                           "responses": null,
                                                           "parameterNames": null,
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa372"
                                       }
                    }, {
                                       "created": 1535722249629,
                                       "modified": 0,
                                       "origin": 0,
                                       "id": "5b8943099f8fc200016aa373",
                                       "name": "testping",
                                       "get": {
                                                           "path": "/api/v1/devices/{deviceId}/ping",
                                                           "responses": [{
                                                                               "code": "200",
                                                                               "description": "ping the device",
                                                                               "expectedValues": ["ping"]
                                                           }, {
                                                                               "code": "503",
                                                                               "description": "service unavailable",
                                                                               "expectedValues": []
                                                           }],
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa373"
                                       },
                                       "put": {
                                                           "path": null,
                                                           "responses": null,
                                                           "parameterNames": null,
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa373"
                                       }
                    }, {
                                       "created": 1535722249630,
                                       "modified": 0,
                                       "origin": 0,
                                       "id": "5b8943099f8fc200016aa374",
                                       "name": "testmessage",
                                       "get": {
                                                           "path": null,
                                                           "responses": null,
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa374"
                                       },
                                       "put": {
                                                           "path": "/api/v1/devices/{deviceId}/message",
                                                           "responses": [{
                                                                               "code": "204",
                                                                               "description": "Set the message.",
                                                                               "expectedValues": []
                                                           }, {
                                                                               "code": "503",
                                                                               "description": "service unavailable",
                                                                               "expectedValues": []
                                                           }],
                                                           "parameterNames": ["message"],
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa374"
                                       }
                    }, {
                                       "created": 1535722249630,
                                       "modified": 0,
                                       "origin": 0,
                                       "id": "5b8943099f8fc200016aa375",
                                       "name": "testquery",
                                       "get": {
                                                           "path": "/api/v1/devices/{deviceId}/query",
                                                           "responses": [{
                                                                               "code": "200",
                                                                               "description": null,
                                                                               "expectedValues": ["randnum"]
                                                           }, {
                                                                               "code": "503",
                                                                               "description": "service unavailable",
                                                                               "expectedValues": []
                                                           }],
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa375"
                                       },
                                       "put": {
                                                           "path": null,
                                                           "responses": null,
                                                           "parameterNames": null,
                                                           "url": "http://edgex-core-command:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa375"
                                       }
                    }]
}

When i try to invoke the ‘randnum’ command URL (see the highlighted code above) we got the following error:

ubuntu@ip-10-0-2-201:~$ curl -v -o - http://localhost:48082/api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa372
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 48082 (#0)
> GET /api/v1/device/5b9f71e09f8fc200016aa37b/command/5b8943099f8fc200016aa372 HTTP/1.1
> Host: localhost:48082
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Date: Tue, 18 Sep 2018 07:27:06 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact

I noticed the following logs on core-command microservice:

edgex-core-command | INFO: 2018/09/18 07:27:05 Issuing GET command to: http://localhost:49982/api/v1/devices/5b9f71e09f8fc200016aa37b/randnum
edgex-core-command | ERROR: 2018/09/18 07:27:06 Get http://localhost:49982/api/v1/devices/5b9f71e09f8fc200016aa37b/randnum: dial tcp 127.0.0.1:49982: getsockopt: connection refused

Could you help me to solve this issue?

Thanks & Regards,
Giovanni

**Comment by giovannipersia** [comment]
Issue resolved, it was due to lack of visibility between docker containers.

**Comment by ljamnal** [comment]
Hi giovannipersia, can you please tell what were the changes. i am also facing the exact same issue using Delhi 0.7.0 ?

**Comment by giovannipersia** [comment]
Hi @ljamnal my issue was related to a visibility lack between docker images. 
Check your docker-compose file and make sure to use the correct hostname when you call core-command REST API’s.
